name: Deploy Static Website to Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy website files
        run: |
          rsync -az --delete \
            --exclude ".git" \
            --exclude ".github" \
            ./ ubuntu@${{ secrets.SERVER_HOST }}:/var/www/html/

      - name: Reload Nginx
        run: |
          ssh ubuntu@${{ secrets.SERVER_HOST }} "sudo systemctl reload nginx"
